{
 "title": "New dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Location",
   "type": "stat",
   "description": "Pune",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "p10" ] } },
   "targets": [
    {
     "rawSql": "SELECT longitude, latitude FROM weather_data LIMIT 50 "
    },
    { "table": "weather_data" }
   ]
  },
  {
   "title": "Average AQI",
   "type": "gauge",
   "description": "Display Average AQI for All parameters\n",
   "gridPos": { "h": 5, "w": 10, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  AVG(pm25_aqi)  as PM25, \r\n  AVG(pm10_aqi)  as PM10, \r\n  AVG(so2_aqi)  as SO2, \r\n  AVG(no2_aqi)  as NO2\r\nFROM aqi_data_new"
    }
   ]
  },
  {
   "title": "pm10_AQI",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT pm10_aqi, \"timestamp\" FROM aqi_data_new LIMIT 50 "
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", pm25_aqi, pm10_aqi, so2_aqi, no2_aqi, nh3_aqi FROM aqi_data_new LIMIT 50 "
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp_ist, temperature_celsius FROM weather_data LIMIT 50 "
    }
   ]
  },
  {
   "title": "Pressure ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT timestamp_ist, pressure FROM weather_data LIMIT 50 "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT wind_speed, humidity FROM weather_data LIMIT 50 "
    }
   ]
  },
  {
   "title": "PM25 VS PM10",
   "type": "xychart",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT pm25_aqi, pm10_aqi FROM aqi_data_new LIMIT 50 "
    }
   ]
  }
 ]
}