{
 "title": "Weather",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"text-align: center; color: #00d4ff; font-size: 24px;\">AIR QUALITY & WEATHER DASHBOARD</h1>\n"
   }
  },
  {
   "title": "AQI",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", aqi \nFROM aqi_data_temp \nWHERE $__timeFilter(timestamp)"
    },
    {
     "rawSql": "SELECT \"timestamp\", forecast_aqi\nFROM aqi_forecast_data \nWHERE $__timeFilter(timestamp)"
    }
   ]
  },
  {
   "title": "Temperature (PUNE)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT timestamp_ist AS \"time\", \n       temperature_celsius AS \"Temperature (°C)\"\nFROM weather_data\nORDER BY timestamp_ist;\n"
    },
    {
     "rawSql": "SELECT timestamp_ist AS \"time\", \n       feels_like_celsius AS \"Feels Like (°C)\"\nFROM weather_data\nORDER BY timestamp_ist;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    MIN(wind_speed) AS \"Min Wind Speed(m/s)\", \n    MAX(wind_speed) AS \"Max Wind Speed(m/s)\"\nFROM weather_data\nWHERE $__timeFilter(timestamp_ist);"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    humidity AS \"Humidity (%)\",\n    timestamp_ist AS \"time\"\nFROM weather_data\nWHERE $__timeFilter(timestamp_ist)\nORDER BY timestamp_ist DESC\nLIMIT 1;\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    pressure AS \"Pressure (hPa)\",\n    timestamp_ist AS \"time\"\nFROM weather_data\nWHERE $__timeFilter(timestamp_ist)\nORDER BY timestamp_ist DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "operato-windrose-panel",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT \n    wind_speed AS \"wind_speed\",\n    wind_deg AS \"wind_direction\",\n    timestamp_ist AS \"time\"\nFROM weather_data\nWHERE $__timeFilter(timestamp_ist)\nORDER BY timestamp_ist DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Wind Speed (m/s)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp_ist AS \"time\", \n       wind_speed AS \"Wind Speed (m/s)\"\nFROM weather_data\nWHERE $__timeFilter(timestamp_ist)\nORDER BY timestamp_ist DESC;\n"
    }
   ]
  },
  {
   "title": "pm2_5",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    date_trunc('hour', timestamp_ist) AS time,  -- Truncating to the nearest hour\n    AVG(pm2_5) AS pm2_5\nFROM\n    aqi_data\nWHERE\n    $__timeFilter(timestamp_ist)  -- Grafana time filter\nGROUP BY\n    time\nORDER BY\n    time ASC;"
    }
   ]
  },
  {
   "type": "geomap",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT latitude, longitude, aqi\nFROM aqi_data_temp\nWHERE $__timeFilter(timestamp)\nORDER by timestamp DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "type": "barchart",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT\n    date_trunc('hour', timestamp_ist) AS time,  -- Truncating to the hour for grouping\n    AVG(pm2_5) AS pm2_5,\n    AVG(pm10) AS pm10,\n    AVG(no2) AS no2,\n    AVG(so2) AS so2\nFROM\n    aqi_data\nWHERE\n    $__timeFilter(timestamp_ist)  -- Grafana time filter\nGROUP BY\n    time\nORDER BY\n    time DESC\nLIMIT 1;"
    }
   ]
  }
 ]
}