{
 "title": "Weather",
 "time": { "from": "now-24h", "to": "now+6h" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Temperature (PUNE)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT timestamp_ist AS \"time\", \n       temperature_celsius AS \"Temperature (°C)\", \n       feels_like_celsius AS \"Feels Like (°C)\"\nFROM weather_data\nORDER BY timestamp_ist;\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    MIN(wind_speed) AS \"Min Wind Speed (m/s)\", \n    MAX(wind_speed) AS \"Max Wind Speed (m/s)\"\nFROM weather_data\nWHERE $__timeFilter(timestamp_ist);"
    }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "operato-windrose-panel",
   "gridPos": { "h": 7, "w": 4, "x": 14, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n    wind_speed AS \"wind_speed\",\n    wind_deg AS \"wind_direction\",\n    timestamp_ist AS \"time\"\nFROM weather_data\nWHERE $__timeFilter(timestamp_ist)\nORDER BY timestamp_ist DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Wind Speed (m/s)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp_ist AS \"time\", \n       wind_speed AS \"Wind Speed (m/s)\"\nFROM weather_data\nWHERE $__timeFilter(timestamp_ist)\nORDER BY timestamp_ist DESC;\n"
    }
   ]
  }
 ]
}