{
 "title": "Weather",
 "time": { "from": "now-24h", "to": "now+6h" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Temperature (PUNE)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT timestamp_ist AS \"time\", \n       temperature_celsius AS \"Temperature (°C)\", \n       feels_like_celsius AS \"Feels Like (°C)\"\nFROM weather_data\nORDER BY timestamp_ist;\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    MIN(wind_speed) AS \"Min Wind Speed (m/s)\", \n    MAX(wind_speed) AS \"Max Wind Speed (m/s)\"\nFROM weather_data\nWHERE $__timeFilter(timestamp_ist);"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    humidity AS \"Humidity (%)\",\n    timestamp_ist AS \"time\"\nFROM weather_data\nWHERE $__timeFilter(timestamp_ist)\nORDER BY timestamp_ist DESC\nLIMIT 1;\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    pressure AS \"Pressure (hPa)\",\n    timestamp_ist AS \"time\"\nFROM weather_data\nWHERE $__timeFilter(timestamp_ist)\nORDER BY timestamp_ist DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "operato-windrose-panel",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT \n    wind_speed AS \"wind_speed\",\n    wind_deg AS \"wind_direction\",\n    timestamp_ist AS \"time\"\nFROM weather_data\nWHERE $__timeFilter(timestamp_ist)\nORDER BY timestamp_ist DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Wind Speed (m/s)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp_ist AS \"time\", \n       wind_speed AS \"Wind Speed (m/s)\"\nFROM weather_data\nWHERE $__timeFilter(timestamp_ist)\nORDER BY timestamp_ist DESC;\n"
    }
   ]
  },
  {
   "title": "pm2_5",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    date_trunc('hour', timestamp_ist) AS time,  -- Truncating to the nearest hour\n    AVG(pm2_5) AS pm2_5\nFROM\n    aqi_data\nWHERE\n    $__timeFilter(timestamp_ist)  -- Grafana time filter\nGROUP BY\n    time\nORDER BY\n    time ASC;"
    }
   ]
  },
  {
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n    date_trunc('hour', timestamp_ist) AS time,  -- Truncating to the hour for grouping\n    AVG(pm2_5) AS pm2_5,\n    AVG(pm10) AS pm10,\n    AVG(no2) AS no2,\n    AVG(so2) AS so2\nFROM\n    aqi_data\nWHERE\n    $__timeFilter(timestamp_ist)  -- Grafana time filter\nGROUP BY\n    time\nORDER BY\n    time DESC\nLIMIT 1;"
    }
   ]
  }
 ]
}